// <auto-generated />
namespace Stacja_paliw.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Initial2identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial2identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201703271911393_Initial2 identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
