// <auto-generated />
namespace Stacja_paliw.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_loyality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_loyality));
        
        string IMigrationMetadata.Id
        {
            get { return "201705060851355_add_loyality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
