// <auto-generated />
namespace Stacja_paliw.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userchanges3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userchanges3));
        
        string IMigrationMetadata.Id
        {
            get { return "201703211002013_user changes3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
