<?xml version="1.0" encoding="utf-8"?><Database Name="ProjZesp_Model" Class="CalendarEventsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:slamnation01.database.windows.net,1433;Initial Catalog=ProjZesp_Model;Persist Security Info=False;User ID=slamnation;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjZesp_ModelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CarWashMonthlyEvents" Member="CarWashMonthlyEvents">
    <Type Name="CarWashMonthlyEvent">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EventStart" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EventEnd" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>