<?xml version="1.0" encoding="utf-8"?><Database Name="ProjZesp_Model" Class="FuelTankParamethersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tcp:slamnation01.database.windows.net,1433;Initial Catalog=ProjZesp_Model;Persist Security Info=False;User ID=slamnation;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ProjZesp_ModelConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FuelTanksParamethers" Member="FuelTanksParamethers">
    <Type Name="FuelTanksParamether">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FuelLevel" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Temperature" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Pressure" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>